#!/usr/bin/env python3

import os
import sys

first_char = None  # First char in font
last_char = None  # Last char in font
pos = {}  # Chars positions
data = []  # Char data

os.chdir(sys.path[0])

for i in range(0, 255):
    if os.path.isfile(str(i) + '.txt'):
        if first_char is None:
            first_char = i
        last_char = i
        with open(str(i) + '.txt') as f:
            lines = [line.strip() for line in f.readlines() if line.strip()]
            pos[i] = len(data)
            data += [len(lines[0]), len(lines), 0]
            k = 0
            for line in lines:
                for char in line:
                    data[-1] |= (char == '1') << k
                    k += 1
                    if k == 8:
                        data.append(0)
                        k = 0

if first_char is None:
    raise FileNotFoundError('No font files found!')

with open('font.h', 'w') as f:
    lines = [
        '#pragma once',
        '',
        '// This file was automatically generated by generate_font.py!',
        '',
        '#include <avr/pgmspace.h>',
        '',
        'constexpr uint8_t c_fontFirstChar = ' + hex(first_char) + ';',
        'constexpr uint8_t c_fontLastChar = ' + hex(last_char) + ';',
        'const uint16_t cp_fontCharOffset[] PROGMEM = {' + ', '.join(
            hex(pos.get(val, 0)) for val in range(first_char, last_char+1)) + '};',
        'const uint8_t cp_fontCharData[] PROGMEM = {' + ', '.join(
            hex(val) for val in data) + '};',
        '',
    ]
    f.write('\n'.join(lines))

print('Done!')
